"""
Master Orchestrator
Coordinates all specialist agents and manages the development workflow
"""

import asyncio
import json
import uuid
from typing import Dict, List, Any, Optional, Set
from dataclasses import dataclass
from enum import Enum
from datetime import datetime

from agents.specialist_agents import AgentFactory, AgentRole, AgentContext
from agents.base_agent import AgentResult
from .task_parser import TaskParser, Task

class OrchestrationStatus(Enum):
    """Status of orchestration process"""
    PENDING = "pending"
    RUNNING = "running"
    COMPLETED = "completed"
    FAILED = "failed"
    CANCELLED = "cancelled"

@dataclass
class OrchestrationResult:
    """Result of orchestration process"""
    orchestration_id: str
    status: OrchestrationStatus
    tasks_completed: int
    tasks_failed: int
    total_tasks: int
    artifacts: Dict[str, Any]
    errors: List[str]
    start_time: datetime
    end_time: Optional[datetime] = None
    duration_seconds: Optional[float] = None
    
    def to_dict(self) -> Dict[str, Any]:
        """Convert to dictionary"""
        return {
            "orchestration_id": self.orchestration_id,
            "status": self.status.value,
            "tasks_completed": self.tasks_completed,
            "tasks_failed": self.tasks_failed,
            "total_tasks": self.total_tasks,
            "completion_rate": (self.tasks_completed / self.total_tasks * 100) if self.total_tasks > 0 else 0,
            "artifacts_count": len(self.artifacts),
            "errors": self.errors,
            "start_time": self.start_time.isoformat(),
            "end_time": self.end_time.isoformat() if self.end_time else None,
            "duration_seconds": self.duration_seconds
        }

class TaskNode:
    """Node in the task execution graph"""
    
    def __init__(self, task: Task):
        self.task = task
        self.status: OrchestrationStatus = OrchestrationStatus.PENDING
        self.dependencies: Set[str] = set(task.dependencies)
        self.dependents: Set[str] = set()
        self.result: Optional[AgentResult] = None
        self.error: Optional[str] = None
        self.start_time: Optional[datetime] = None
        self.end_time: Optional[datetime] = None

class MasterOrchestrator:
    """
    Master orchestrator that coordinates all specialist agents
    Manages task dependencies, parallel execution, and artifact assembly
    """
    
    def __init__(self):
        self.task_parser = TaskParser()
        self.agent_factory = AgentFactory()
        self.task_graph: Dict[str, TaskNode] = {}
        self.execution_order: List[str] = []
        self.context: Optional[AgentContext] = None
        self.artifacts: Dict[str, Any] = {}
        self.orchestration_results: Dict[str, OrchestrationResult] = {}
        
    async def orchestrate(self, project_description: str, 
                         tech_stack: Optional[Dict[str, str]] = None,
                         requirements: Optional[List[str]] = None) -> OrchestrationResult:
        """
        Orchestrate the entire MVP generation process
        
        Args:
            project_description: Natural language description of the project
            tech_stack: Technology stack preferences
            requirements: Specific requirements
            
        Returns:
            OrchestrationResult with all artifacts and status
        """
        orchestration_id = f"orch_{uuid.uuid4().hex[:8]}"
        start_time = datetime.now()
        
        try:
            # 1. Parse project description into tasks
            print(f"[{orchestration_id}] Parsing project description...")
            tasks = self.task_parser.parse_natural_language(project_description)
            
            # 2. Create execution context
            self.context = AgentContext(
                project_name="Generated Project",
                project_description=project_description,
                requirements=requirements or [],
                tech_stack=tech_stack or {"backend": "fastapi", "frontend": "nextjs"},
                constraints=["Generated by MVP Factory"]
            )
            
            # 3. Build task execution graph
            print(f"[{orchestration_id}] Building task graph ({len(tasks)} tasks)...")
            self._build_task_graph(tasks)
            
            # 4. Determine execution order (topological sort)
            self._determine_execution_order()
            
            # 5. Execute tasks in parallel where possible
            print(f"[{orchestration_id}] Executing tasks...")
            await self._execute_tasks()
            
            # 6. Assemble artifacts
            print(f"[{orchestration_id}] Assembling artifacts...")
            self._assemble_artifacts()
            
            # 7. Create result
            end_time = datetime.now()
            duration = (end_time - start_time).total_seconds()
            
            result = OrchestrationResult(
                orchestration_id=orchestration_id,
                status=OrchestrationStatus.COMPLETED,
                tasks_completed=sum(1 for node in self.task_graph.values() 
                                  if node.status == OrchestrationStatus.COMPLETED),
                tasks_failed=sum(1 for node in self.task_graph.values() 
                                if node.status == OrchestrationStatus.FAILED),
                total_tasks=len(self.task_graph),
                artifacts=self.artifacts,
                errors=[node.error for node in self.task_graph.values() 
                       if node.error],
                start_time=start_time,
                end_time=end_time,
                duration_seconds=duration
            )
            
            self.orchestration_results[orchestration_id] = result
            
            print(f"[{orchestration_id}] Orchestration completed in {duration:.1f}s")
            return result
            
        except Exception as e:
            end_time = datetime.now()
            duration = (end_time - start_time).total_seconds()
            
            result = OrchestrationResult(
                orchestration_id=orchestration_id,
                status=OrchestrationStatus.FAILED,
                tasks_completed=0,
                tasks_failed=len(self.task_graph),
                total_tasks=len(self.task_graph),
                artifacts={},
                errors=[f"Orchestration failed: {str(e)}"],
                start_time=start_time,
                end_time=end_time,
                duration_seconds=duration
            )
            
            self.orchestration_results[orchestration_id] = result
            print(f"[{orchestration_id}] Orchestration failed: {str(e)}")
            return result
    
    def _build_task_graph(self, tasks: List[Task]):
        """Build execution graph from tasks"""
        self.task_graph.clear()
        
        # Create nodes
        for task in tasks:
            node = TaskNode(task)
            self.task_graph[task.task_id] = node
        
        # Build dependency relationships
        for task_id, node in self.task_graph.items():
            for dep_id in node.dependencies:
                if dep_id in self.task_graph:
                    self.task_graph[dep_id].dependents.add(task_id)
                else:
                    print(f"Warning: Dependency {dep_id} not found for task {task_id}")
    
    def _determine_execution_order(self):
        """Determine topological order for task execution"""
        # Simple topological sort (Kahn's algorithm)
        indegree = {task_id: len(node.dependencies) 
                   for task_id, node in self.task_graph.items()}
        
        queue = [task_id for task_id, deg in indegree.items() if deg == 0]
        self.execution_order = []
        
        while queue:
            task_id = queue.pop(0)
            self.execution_order.append(task_id)
            
            for dependent in self.task_graph[task_id].dependents:
                indegree[dependent] -= 1
                if indegree[dependent] == 0:
                    queue.append(dependent)
        
        if len(self.execution_order) != len(self.task_graph):
            print("Warning: Cycle detected in task dependencies")
    
    async def _execute_tasks(self):
        """Execute tasks respecting dependencies"""
        # Group tasks by dependency level for parallel execution
        task_levels = self._group_tasks_by_level()
        
        for level, task_ids in enumerate(task_levels):
            print(f"  Executing level {level + 1} ({len(task_ids)} tasks)...")
            
            # Execute all tasks in this level in parallel
            tasks = [self._execute_single_task(task_id) for task_id in task_ids]
            results = await asyncio.gather(*tasks, return_exceptions=True)
            
            # Process results
            for task_id, result in zip(task_ids, results):
                node = self.task_graph[task_id]
                
                if isinstance(result, Exception):
                    node.status = OrchestrationStatus.FAILED
                    node.error = str(result)
                    print(f"    Task {task_id} failed: {str(result)}")
                else:
                    node.status = OrchestrationStatus.COMPLETED
                    node.result = result
                    print(f"    Task {task_id} completed successfully")
    
    def _group_tasks_by_level(self) -> List[List[str]]:
        """Group tasks by dependency level for parallel execution"""
        levels = []
        remaining_tasks = set(self.task_graph.keys())
        
        while remaining_tasks:
            # Find tasks with all dependencies satisfied
            level_tasks = []
            for task_id in list(remaining_tasks):
                node = self.task_graph[task_id]
                
                # Check if all dependencies are completed
                deps_completed = all(
                    dep_id not in remaining_tasks  # Dependency is in previous level
                    for dep_id in node.dependencies
                )
                
                if deps_completed:
                    level_tasks.append(task_id)
            
            if not level_tasks:
                # Circular dependency or error
                break
            
            levels.append(level_tasks)
            remaining_tasks -= set(level_tasks)
        
        return levels
    
    async def _execute_single_task(self, task_id: str) -> AgentResult:
        """Execute a single task with appropriate agent"""
        node = self.task_graph[task_id]
        task = node.task
        
        # Map task type to agent role
        role_mapping = {
            "create_api": AgentRole.BACKEND_ENGINEER,
            "create_ui": AgentRole.FRONTEND_ENGINEER,
            "setup_database": AgentRole.BACKEND_ENGINEER,
            "implement_auth": AgentRole.BACKEND_ENGINEER,
            "deploy": AgentRole.DEVOPS_ENGINEER,
            "test": AgentRole.TESTING_ENGINEER
        }
        
        agent_role = role_mapping.get(task.task_type.value, AgentRole.BACKEND_ENGINEER)
        
        # Create and execute agent
        agent = self.agent_factory.create_agent(agent_role)
        
        node.start_time = datetime.now()
        try:
            response = await agent.execute(task.description, self.context)
            node.end_time = datetime.now()
            return response
        except Exception as e:
            node.end_time = datetime.now()
            raise e
    
    def _assemble_artifacts(self):
        """Assemble all agent artifacts into a coherent project"""
        self.artifacts = {
            "project_metadata": {
                "name": self.context.project_name if self.context else "Unnamed",
                "description": self.context.project_description if self.context else "",
                "generated_at": datetime.now().isoformat(),
                "orchestration_id": list(self.orchestration_results.keys())[-1] if self.orchestration_results else ""
            },
            "backend": {},
            "frontend": {},
            "devops": {},
            "testing": {},
            "task_results": {}
        }
        
        # Aggregate artifacts by category
        for task_id, node in self.task_graph.items():
            if node.result and node.result.success:
                # Store task result
                self.artifacts["task_results"][task_id] = {
                    "task": node.task.to_dict(),
                    "agent": node.task.agent_type,
                    "result": node.result.to_dict()
                }
                
                # Categorize artifacts
                if node.task.agent_type == "backend_agent":
                    self.artifacts["backend"].update(node.result.artifacts)
                elif node.task.agent_type == "frontend_agent":
                    self.artifacts["frontend"].update(node.result.artifacts)
                elif node.task.agent_type == "devops_agent":
                    self.artifacts["devops"].update(node.result.artifacts)
                elif node.task.agent_type == "testing_agent":
                    self.artifacts["testing"].update(node.result.artifacts)
        
        # Generate project structure
        self._generate_project_structure()
    
    def _generate_project_structure(self):
        """Generate recommended project structure"""
        self.artifacts["project_structure"] = {
            "backend": [
                "src/",
                "src/__init__.py",
                "src/main.py",
                "src/api/",
                "src/models/",
                "src/database/",
                "src/auth/",
                "requirements.txt",
                "Dockerfile",
                ".env.example"
            ],
            "frontend": [
                "src/",
                "src/components/",
                "src/pages/",
                "src/styles/",
                "src/utils/",
                "package.json",
                "next.config.js",
                "tailwind.config.js",
                "Dockerfile"
            ],
            "devops": [
                "docker-compose.yml",
                ".github/workflows/",
                "deployment/",
                "scripts/"
            ],
            "testing": [
                "tests/",
                "tests/unit/",
                "tests/integration/",
                "tests/e2e/",
                "jest.config.js",
                "pytest.ini"
            ]
        }
    
    def get_status(self, orchestration_id: str) -> Optional[OrchestrationResult]:
        """Get status of a specific orchestration"""
        return self.orchestration_results.get(orchestration_id)
    
    def get_all_results(self) -> List[Dict[str, Any]]:
        """Get all orchestration results"""
        return [result.to_dict() for result in self.orchestration_results.values()]
    
    def generate_report(self, orchestration_id: str) -> Dict[str, Any]:
        """Generate detailed report for orchestration"""
        result = self.get_status(orchestration_id)
        if not result:
            return {"error": "Orchestration not found"}
        
        report = {
            "summary": result.to_dict(),
            "task_breakdown": {
                "completed": result.tasks_completed,
                "failed": result.tasks_failed,
                "total": result.total_tasks,
                "success_rate": (result.tasks_completed / result.total_tasks * 100) if result.total_tasks > 0 else 0
            },
            "artifact_summary": {
                "backend_artifacts": len(self.artifacts.get("backend", {})),
                "frontend_artifacts": len(self.artifacts.get("frontend", {})),
                "devops_artifacts": len(self.artifacts.get("devops", {})),
                "testing_artifacts": len(self.artifacts.get("testing", {}))
            },
            "performance_metrics": {
                "total_duration_seconds": result.duration_seconds,
                "tasks_per_minute": (result.total_tasks / (result.duration_seconds / 60)) if result.duration_seconds else 0,
                "average_task_time": (result.duration_seconds / result.total_tasks) if result.total_tasks else 0
            }
        }
        
        return report

# Convenience functions
async def create_mvp(project_description: str, 
                    tech_stack: Optional[Dict[str, str]] = None,
                    requirements: Optional[List[str]] = None) -> Dict[str, Any]:
    """
    High-level function to create an MVP from description
    
    Args:
        project_description: Natural language description
        tech_stack: Optional tech stack override
        requirements: Optional specific requirements
        
    Returns:
        Dictionary with MVP artifacts and metadata
    """
    orchestrator = MasterOrchestrator()
    
    # Run orchestration
    result = await orchestrator.orchestrate(project_description, tech_stack, requirements)
    
    # Generate report
    report = orchestrator.generate_report(result.orchestration_id)
    
    return {
        "orchestration_result": result.to_dict(),
        "report": report,
        "artifacts": orchestrator.artifacts,
        "success": result.status == OrchestrationStatus.COMPLETED
    }

if __name__ == "__main__":
    # Example usage
    example_project = """
    Create a task management application with:
    1. User authentication (login/register)
    2. REST API for CRUD operations on tasks
    3. React frontend with clean UI
    4. PostgreSQL database
    5. Deployment to Vercel
    6. Comprehensive testing
    """
    
    async def run_example():
        result = await create_mvp(
            project_description=example_project,
            tech_stack={
                "backend": "fastapi",
                "frontend": "nextjs",
                "database": "postgresql",
                "deployment": "vercel"
            }
        )
        
        print("MVP Creation Result:")
        print(json.dumps(result, indent=2))
    
    # Run the example
    asyncio.run(run_example())
